# Site settings
description: > # this means to ignore newlines until "baseurl:"
  Jeff Cho
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gojeffcho.github.io" # the base hostname & protocol for your site
startyear: 2018

# User settings
title: Jeff Cho
name: Jeff Cho
email: site@jeffcho.com

twitter_username: gojeffcho
github_username:  gojeffcho
linkedin_username: gojeffcho
facebook_username: gojeffcho

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data", "superscript"]
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

# Site-wide variables
keywords: computer science, computing science, games, game design, game development, programming, programmer, development, developer, software, software engineer, software engineering, social media, technology, canada, university of alberta
copyright: Copyright (c) Jeff Cho

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
#  - jemoji
